services:
  neo4j:
    image: neo4j:5.6  
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password  
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt 
    volumes:
      - neo4j_data:/data  
      - neo4j_logs:/logs  
      - neo4j_import:/import  
      - neo4j_plugins:/plugins  

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
